# Generated by Django 3.0.6 on 2020-12-06 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MarketingCategory',
            new_name='Marketing',
        ),
    ]
