# Generated by Django 3.0.6 on 2020-12-11 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0002_auto_20201206_2349'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Marketing',
            new_name='MarketingCategory',
        ),
    ]
