# Generated by Django 3.0.6 on 2020-11-22 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
                ('marketing', models.CharField(blank=True, max_length=30, null=True)),
                ('marketing_image', models.ImageField(blank=True, null=True, upload_to='pictures/')),
                ('new_arrival', models.CharField(blank=True, max_length=30, null=True)),
                ('discount', models.CharField(blank=True, max_length=30, null=True)),
                ('sale_off', models.CharField(blank=True, max_length=30, null=True)),
                ('name', models.CharField(max_length=300)),
                ('price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('description', models.TextField(blank=True)),
                ('digital', models.BooleanField(blank=True, default=False, null=True)),
                ('operation_system', models.CharField(blank=True, max_length=300)),
                ('pc_model', models.CharField(blank=True, max_length=300)),
                ('appearance', models.CharField(blank=True, max_length=300)),
                ('display', models.CharField(blank=True, max_length=300)),
                ('display_definition', models.CharField(blank=True, max_length=300)),
                ('display_covering', models.CharField(blank=True, max_length=300)),
                ('cpu_name', models.CharField(blank=True, max_length=300)),
                ('cpu_model', models.CharField(blank=True, max_length=300)),
                ('cpu_core', models.CharField(blank=True, max_length=300)),
                ('cpu_freq', models.CharField(blank=True, max_length=300)),
                ('operation_memory', models.CharField(blank=True, max_length=300)),
                ('gpu', models.CharField(blank=True, max_length=300)),
                ('memory', models.CharField(blank=True, max_length=300)),
                ('camera', models.CharField(blank=True, max_length=300)),
                ('peripheral', models.CharField(blank=True, max_length=300)),
                ('battery_capacity', models.CharField(blank=True, max_length=300)),
                ('battery_power', models.CharField(blank=True, max_length=300)),
                ('process_time', models.CharField(blank=True, max_length=300)),
                ('depth', models.CharField(blank=True, max_length=300)),
                ('height', models.CharField(blank=True, max_length=300)),
                ('width', models.CharField(blank=True, max_length=300)),
                ('weight', models.CharField(blank=True, max_length=300)),
                ('published', models.DateTimeField(verbose_name='publishing date')),
                ('slug', models.SlugField(blank=True, null=True)),
                ('image', models.FileField(upload_to='pictures/')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.FileField(upload_to='pictures/')),
                ('product_detailed', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='product.Product')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('text', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='product.Product')),
            ],
            options={
                'ordering': ['created_on'],
            },
        ),
    ]
