# Generated by Django 3.0.6 on 2020-11-23 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20201123_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='marketing',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='new_arrival',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='sale_off',
            field=models.BooleanField(default=False),
        ),
    ]
