# Generated by Django 3.0.6 on 2020-11-25 11:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_viewedproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='viewedproduct',
            name='date_viewed',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
