# Generated by Django 3.0.6 on 2020-11-25 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_viewedproduct_date_viewed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='viewedproduct',
            name='date_viewed',
        ),
    ]
