# Generated by Django 3.0.6 on 2020-11-25 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_remove_viewedproduct_date_viewed'),
    ]

    operations = [
        migrations.AddField(
            model_name='viewedproduct',
            name='session',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
