# Generated by Django 3.0.6 on 2020-12-05 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_auto_20201205_1347'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(blank=True, max_length=300, null=True)),
                ('category_image_mobile', models.FileField(blank=True, null=True, upload_to='category/')),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='mobile_image',
        ),
    ]
