# Generated by Django 3.0.6 on 2020-12-05 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_auto_20201205_1443'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='CategoryForMobile',
        ),
    ]
