# Generated by Django 3.0.6 on 2020-12-05 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_auto_20201205_1550'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ficc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marketing_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
