# Generated by Django 3.0.6 on 2020-12-05 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_ficc'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ficc',
        ),
    ]
