# Generated by Django 3.0.6 on 2020-12-05 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_auto_20201205_1650'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MarketingCategoryForMobile',
        ),
        migrations.DeleteModel(
            name='ProductCategoryForMobile',
        ),
    ]
