# Generated by Django 3.0.6 on 2020-12-12 19:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0018_auto_20201205_1851'),
    ]

    operations = [
        migrations.AddField(
            model_name='viewedproduct',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='viewedproduct',
            name='session',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
