# Generated by Django 3.0.6 on 2020-12-12 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0019_auto_20201213_0001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viewedproduct',
            name='date',
            field=models.DateTimeField(verbose_name='date'),
        ),
    ]
